{ DTRACE_NET_SERVER_CONNECTION: [Function],
  DTRACE_NET_STREAM_END: [Function],
  DTRACE_HTTP_SERVER_REQUEST: [Function],
  DTRACE_HTTP_SERVER_RESPONSE: [Function],
  DTRACE_HTTP_CLIENT_REQUEST: [Function],
  DTRACE_HTTP_CLIENT_RESPONSE: [Function],
  COUNTER_NET_SERVER_CONNECTION: [Function],
  COUNTER_NET_SERVER_CONNECTION_CLOSE: [Function],
  COUNTER_HTTP_SERVER_REQUEST: [Function],
  COUNTER_HTTP_SERVER_RESPONSE: [Function],
  COUNTER_HTTP_CLIENT_REQUEST: [Function],
  COUNTER_HTTP_CLIENT_RESPONSE: [Function],
  global: [Circular],
  process:
   process {
     title: '�pO',
     version: 'v7.0.0',
     moduleLoadList:
      [ 'Binding contextify',
        'Binding natives',
        'NativeModule events',
        'NativeModule util',
        'Binding uv',
        'NativeModule buffer',
        'Binding buffer',
        'Binding util',
        'NativeModule internal/util',
        'NativeModule timers',
        'Binding timer_wrap',
        'NativeModule internal/linkedlist',
        'NativeModule assert',
        'NativeModule internal/process',
        'Binding config',
        'NativeModule internal/process/warning',
        'NativeModule internal/process/next_tick',
        'NativeModule internal/process/promises',
        'NativeModule internal/process/stdio',
        'Binding constants',
        'NativeModule path',
        'NativeModule module',
        'NativeModule internal/module',
        'NativeModule vm',
        'NativeModule fs',
        'Binding fs',
        'NativeModule stream',
        'NativeModule _stream_readable',
        'NativeModule internal/streams/BufferList',
        'NativeModule _stream_writable',
        'NativeModule _stream_duplex',
        'NativeModule _stream_transform',
        'NativeModule _stream_passthrough',
        'Binding fs_event_wrap',
        'NativeModule internal/fs',
        'NativeModule console',
        'Binding tty_wrap',
        'NativeModule tty',
        'NativeModule net',
        'NativeModule internal/net',
        'Binding cares_wrap',
        'Binding tcp_wrap',
        'Binding pipe_wrap',
        'Binding stream_wrap',
        'Binding signal_wrap' ],
     versions:
      { http_parser: '2.7.0',
        node: '7.0.0',
        v8: '5.4.500.36',
        uv: '1.9.1',
        zlib: '1.2.8',
        ares: '1.10.1-DEV',
        icu: '57.1',
        modules: '51',
        openssl: '1.0.2j' },
     arch: 'x64',
     platform: 'win32',
     release:
      { name: 'node',
        sourceUrl: 'https://nodejs.org/download/release/v7.0.0/node-v7.0.0.tar.gz',
        headersUrl: 'https://nodejs.org/download/release/v7.0.0/node-v7.0.0-headers.tar.gz',
        libUrl: 'https://nodejs.org/download/release/v7.0.0/win-x64/node.lib' },
     argv:
      [ 'D:\\Program Files\\nodejs\\node.exe',
        'E:\\learngit\\learnNodeJs\\authorityBook\\nodeCore\\global.js' ],
     execArgv: [],
     env:
      { ACLOCAL_PATH: '/mingw64/share/aclocal:/usr/share/aclocal',
        ALLUSERSPROFILE: 'C:\\ProgramData',
        APPDATA: 'C:\\Users\\ZH\\AppData\\Roaming',
        'asl.log': 'Destination=file',
        CLASSPATH: '.;D:\\Program Files\\tomcat\\apache-tomcat-8.0.30\\lib\\servlet-api.jar',
        COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files',
        'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
        CommonProgramW6432: 'C:\\Program Files\\Common Files',
        COMPUTERNAME: 'ZH-PC',
        COMSPEC: 'C:\\Windows\\system32\\cmd.exe',
        DISPLAY: 'needs-to-be-defined',
        EXEPATH: 'F:\\git应用程序\\Git',
        FP_NO_HOST_CHECK: 'NO',
        GRADLE_HOME: 'D:\\Program Files\\Java\\gradle-2.6',
        HOME: 'C:\\Users\\ZH',
        HOMEDRIVE: 'C:',
        HOMEPATH: '\\Users\\ZH',
        HOSTNAME: 'ZH-PC',
        INFOPATH: '/usr/local/info:/usr/share/info:/usr/info:/share/info:',
        JAVA_HOME: 'D:\\Program Files\\Java\\jdk1.8.0_60',
        LANG: 'zh_CN.UTF-8',
        LOCALAPPDATA: 'C:\\Users\\ZH\\AppData\\Local',
        LOGONSERVER: '\\\\ZH-PC',
        MANPATH: '/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man:',
        MAVEN_HOME: 'F:\\maven\\apache-maven-3.3.9',
        MSYSTEM: 'MINGW64',
        MYSQL_HOME: 'C:\\Program Files\\MySQL\\MySQL Server 5.6',
        NUMBER_OF_PROCESSORS: '8',
        OS: 'Windows_NT',
        PATH: 'C:\\Users\\ZH\\bin;F:\\git应用程序\\Git\\mingw64\\bin;F:\\git应用程序\\Git\\usr\\local\\bin;F:\\git应用程序\\Git\\usr\\bin;F:\\git应用程序\\Git\\
usr\\bin;F:\\git应用程序\\Git\\mingw64\\bin;F:\\git应用程序\\Git\\usr\\bin;C:\\U
sers\\ZH\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;D:\\app\\ZH\\product\\11.1
.0\\db_1\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\
Windows\\System32\\WindowsPowerShell\\v1.0;D:\\Program Files\\Java\\jdk1.8.0_60\
\bin;D:\\Program Files\\Java\\jdk1.8.0_60\\jre\\bin;D:\\Program Files\\Java\\gra
dle-2.6\\bin;D:\\Program Files\\HashiCorp\\Vagrant\\bin;D:\\Program Files\\tomca
t\\apache-tomcat-8.0.30\\bin;C:\\Program Files\\TortoiseSVN\\bin;F:\\maven\\apac
he-maven-3.3.9\\bin;C:\\Program Files\\MySQL\\MySQL Server 5.6\\bin;D:\\Program
Files\\nodejs;C:\\Users\\ZH\\AppData\\Roaming\\npm;F:\\git应用程序\\Git\\usr\\bi
n\\vendor_perl;F:\\git应用程序\\Git\\usr\\bin\\core_perl',
        PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
        PKG_CONFIG_PATH: '/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig',
        PLINK_PROTOCOL: 'ssh',
        PRINTER: 'Microsoft XPS Document Writer',
        PROCESSOR_ARCHITECTURE: 'AMD64',
        PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
        PROCESSOR_LEVEL: '6',
        PROCESSOR_REVISION: '3c03',
        ProgramData: 'C:\\ProgramData',
        PROGRAMFILES: 'C:\\Program Files',
        'ProgramFiles(x86)': 'C:\\Program Files (x86)',
        ProgramW6432: 'C:\\Program Files',
        PS1: '\\[\\033]0;$TITLEPREFIX:${PWD//[^[:ascii:]]/?}\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\[\\033[0m\\]\\n$ ',
        PSModulePath: 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
        PUBLIC: 'C:\\Users\\Public',
        PWD: '/e/learngit/learnNodeJs/authorityBook/nodeCore',
        SESSIONNAME: 'Console',
        SHELL: 'F:\\git应用程序\\Git\\usr\\bin\\bash',
        SHLVL: '1',
        SSH_ASKPASS: '/mingw64/libexec/git-core/git-gui--askpass',
        SYSTEMDRIVE: 'C:',
        SYSTEMROOT: 'C:\\Windows',
        TEMP: 'C:\\Users\\ZH\\AppData\\Local\\Temp',
        TERM: 'xterm',
        TMP: 'C:\\Users\\ZH\\AppData\\Local\\Temp',
        TMPDIR: 'C:\\Users\\ZH\\AppData\\Local\\Temp',
        TOMCAT_HOME: 'D:\\Program Files\\tomcat\\apache-tomcat-8.0.30',
        USERDOMAIN: 'ZH-PC',
        USERNAME: 'ZH',
        USERPROFILE: 'C:\\Users\\ZH',
        WINDIR: 'C:\\Windows',
        windows_tracing_flags: '3',
        windows_tracing_logfile: 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log',
        _: '/usr/bin/winpty' },
     pid: 6260,
     features:
      { debug: false,
        uv: true,
        ipv6: true,
        tls_npn: true,
        tls_alpn: true,
        tls_sni: true,
        tls_ocsp: true,
        tls: true },
     _needImmediateCallback: false,
     execPath: 'D:\\Program Files\\nodejs\\node.exe',
     debugPort: 5858,
     _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
     _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
     _getActiveRequests: [Function: _getActiveRequests],
     _getActiveHandles: [Function: _getActiveHandles],
     reallyExit: [Function: reallyExit],
     abort: [Function: abort],
     chdir: [Function: chdir],
     cwd: [Function: cwd],
     umask: [Function: umask],
     _kill: [Function: _kill],
     _debugProcess: [Function: _debugProcess],
     _debugPause: [Function: _debugPause],
     _debugEnd: [Function: _debugEnd],
     hrtime: [Function: hrtime],
     cpuUsage: [Function: cpuUsage],
     dlopen: [Function: dlopen],
     uptime: [Function: uptime],
     memoryUsage: [Function: memoryUsage],
     binding: [Function: binding],
     _linkedBinding: [Function: _linkedBinding],
     _setupDomainUse: [Function: _setupDomainUse],
     _events:
      { warning: [Function],
        newListener: [Function],
        removeListener: [Function],
        SIGWINCH: [Object] },
     _rawDebug: [Function],
     _eventsCount: 4,
     domain: null,
     _maxListeners: undefined,
     _fatalException: [Function],
     _exiting: false,
     assert: [Function],
     config: { target_defaults: [Object], variables: [Object] },
     emitWarning: [Function],
     nextTick: [Function: nextTick],
     _tickCallback: [Function: _tickCallback],
     _tickDomainCallback: [Function: _tickDomainCallback],
     stdout: [Getter],
     stderr: [Getter],
     stdin: [Getter],
     openStdin: [Function],
     exit: [Function],
     kill: [Function],
     argv0: 'node.exe',
     mainModule:
      Module {
        id: '.',
        exports: {},
        parent: null,
        filename: 'E:\\learngit\\learnNodeJs\\authorityBook\\nodeCore\\global.js',
        loaded: false,
        children: [],
        paths: [Object] } },
  Buffer:
   { [Function: Buffer]
     poolSize: 8192,
     from: [Function],
     alloc: [Function],
     allocUnsafe: [Function],
     allocUnsafeSlow: [Function],
     isBuffer: [Function: isBuffer],
     compare: [Function: compare],
     isEncoding: [Function],
     concat: [Function],
     byteLength: [Function: byteLength] },
  clearImmediate: [Function],
  clearInterval: [Function],
  clearTimeout: [Function],
  setImmediate: [Function],
  setInterval: [Function],
  setTimeout: [Function],
  console: [Getter] 
  }
